name: Tests
on: push

jobs:
  test-js:
    name: JavaScript tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm install
      
      - name: Install test reporter
        run: npm install mocha-github-actions-reporter

      - name: Run tests
        run: npm run test -- --reporter mocha-github-actions-reporter
